TestApp.RegistrationEmployee/src/TestApp.RegistrationEmployee.Web/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using TestApp.RegistrationEmployee.Core.Entities;
using TestApp.RegistrationEmployee.Core.Interfaces;
using TestApp.RegistrationEmployee.Web.Filters;
using TestApp.RegistrationEmployee.Web.ViewModels;

namespace TestApp.RegistrationEmployee.Web.Controllers
{
    public class CompanyController : Controller
    {
        private readonly IRepository<Company> _repository;
        public CompanyController(IRepository<Company> repository)
        {
            _repository = repository;
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var company = await _repository.ListAsync();
            var companyViewModel = company
                .Select(s => new CompanyViewModel
                {
                    Name = s.Name,
                    OrganizationalAndLegalForm = s.OrganizationalAndLegalForm
                });

            return View(companyViewModel);
        }

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateModel]
        public async Task<IActionResult> Create(CompanyViewModel model)
        {
            Company company = new Company
            {
                Name = model.Name,
                OrganizationalAndLegalForm = model.OrganizationalAndLegalForm
            };

            try
            {
                await _repository.AddAsync(company);
                await _repository.SaveChangesAsync();
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }

            return RedirectToAction("List");
        }


        public async Task<IActionResult> Edit(string id)
        {
            var company = await _repository.GetByNameAsync(id);
            if (company == null)
                return NotFound();

            return View(CompanyViewModel.FromCompany(company));
        }

        [HttpPost]
        [ValidateModel]
        public async Task<IActionResult> Edit(CompanyViewModel model)
        {
            var company = await _repository.GetByNameAsync(model.Name);
            if (company == null)
                return NoContent();

            company.Name = model.Name;
            company.OrganizationalAndLegalForm = model.OrganizationalAndLegalForm;

            await _repository.UpdateAsync(company);
            await _repository.SaveChangesAsync();

            return RedirectToAction("List");
        }

        public async Task<ActionResult> Delete(string id)
        {
            var company = await _repository.GetByNameAsync(id);

            if (company != null)
                await _repository.DeleteAsync(company);

            return RedirectToAction("List");
        }

    }
}

TestApp.RegistrationEmployee/src/TestApp.RegistrationEmployee.Web/Controllers/EmployeeController.cs
#nullable enable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.DependencyInjection;
using TestApp.RegistrationEmployee.Core.Entities;
using TestApp.RegistrationEmployee.Core.Interfaces;
using TestApp.RegistrationEmployee.Web.Filters;
using TestApp.RegistrationEmployee.Web.ViewModels;

namespace TestApp.RegistrationEmployee.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IRepository<Employee> _repository;
        private readonly IRepository<Company> _repositoryComp;
        public EmployeeController(
            IRepository<Employee> repository,
            IRepository<Company> repositoryComp)
        {
            _repository = repository;
            _repositoryComp = repositoryComp;
        }

        [HttpGet]
        public async Task<IActionResult> List(string company, string name)
        {
            ViewBag.Companies = new SelectList(
               await _repositoryComp.ListAsync(),
                "Name",
                "Name");

            var employees = await _repository.ListAsync();

            var employeesViewModel = employees
                .Select(s => new EmployeeViewModel
                {
                    FirstName = s.Name,
                    SecondName = s.SecondName,
                    LastName = s.LastName,
                    EmploymentDate = s.EmploymentDate,
                    Position = s.Position,
                    Company = _repositoryComp.GetByIdAsync(s.CompanyId).Result.Name
                });

            if (company != null && company != "All")
                employeesViewModel = employeesViewModel.Where(p => p.Company == company);

            if (!String.IsNullOrEmpty(name))
                employeesViewModel = employeesViewModel.Where(p => p.FirstName.Contains(name));

            return View(employeesViewModel);
        }

        public IActionResult Create() => View();

        [HttpPost]
        [ValidateModel]
        public async Task<IActionResult> Create(EmployeeViewModel model)
        {
            Employee employee = new Employee
            {
                Name = model.FirstName,
                SecondName = model.SecondName,
                LastName = model.LastName,
                EmploymentDate = model.EmploymentDate,
                Position = model.Position,
                Company = await _repositoryComp.GetByNameAsync(model.Company)
            };

            try
            {
                await _repository.AddAsync(employee);
                await _repository.SaveChangesAsync();
            }
            catch (Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }

            return RedirectToAction("List");
        }


        public async Task<IActionResult> Edit(string id)
        {
            var employee = await _repository.GetByNameAsync(id);
            if (employee == null)
                return NotFound();

            return View(EmployeeViewModel.FromEmployee(employee));
        }

        [HttpPost]
        [ValidateModel]
        public async Task<IActionResult> Edit(EmployeeViewModel model)
        {
            var employee = await _repository.GetByNameAsync(model.FirstName);
            if (employee == null)
                return NoContent();

            employee.Name = model.FirstName;
            employee.SecondName = model.SecondName;
            employee.LastName = model.LastName;
            employee.EmploymentDate = model.EmploymentDate;
            employee.Position = model.Position;
            employee.Company = await _repositoryComp.GetByNameAsync(model.Company);

            await _repository.UpdateAsync(employee);
            await _repository.SaveChangesAsync();

            return RedirectToAction("List");
        }

        public async Task<ActionResult> Delete(string id)
        {
            var employee = await _repository.GetByNameAsync(id);

            if (employee != null)
                await _repository.DeleteAsync(employee);

            return RedirectToAction("List");
        }

    }
}

TestApp.RegistrationEmployee/src/TestApp.RegistrationEmployee.Web/Views/Shared/FooterPartial.cshtml
<footer id="footer">
    <section>
        <form method="post" asp-controller="Home" asp-action="SendMessage">
            <div class="fields">
                <div class="field">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" />
                </div>
                <div class="field">
                    <label for="email">Email</label>
                    <input type="text" name="email" id="email" />
                </div>
                <div class="field">
                    <label for="message">Message</label>
                    <textarea name="message" id="message" rows="3"></textarea>
                </div>
            </div>
            <ul class="actions">
                <li><input type="submit" value="Send Message" /></li>
            </ul>
        </form>
    </section>
    <section class="split contact">
        <section class="alt">
            <h3>Address</h3>
            <p>
                1234 Somewhere Road #87257<br />
                Nashville, TN 00000-0000
            </p>
        </section>
        <section>
            <h3>Phone</h3>
            <p><a href="#">+375-(29)-243-63-02</a></p>
        </section>
        <section>
            <h3>Email</h3>
            <p><a href="https://mail.ru/">denis_aleksandrov_12@mail.ru</a></p>
        </section>
        <section>
            <h3>Social</h3>
            <ul class="icons alt">
                <li><a href="https://www.linkedin.com/in/denis-aleksandrov-000976211/" class="icon brands alt fa-twitter"><span class="label">VK</span></a></li>
                <li><a href="#" class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
                <li><a href="https://www.linkedin.com/in/denis-aleksandrov-000976211/" class="icon brands alt fa-github"><span class="label">LinkedIn</span></a></li>
            </ul>
        </section>
    </section>
</footer>

TestApp.RegistrationEmployee/src/TestApp.RegistrationEmployee.Web/Views/Shared/ScripsPartial.cshtml
<script src="~/js/jquery.min.js"></script>
<script src="~/js/jquery.scrollex.min.js"></script>
<script src="~/js/jquery.scrolly.min.js"></script>
<script src="~/js/browser.min.js"></script>
<script src="~/js/breakpoints.min.js"></script>
<script src="~/js/util.js"></script>
<script src="~/js/main.js"></script>

TestApp.RegistrationEmployee/src/TestApp.RegistrationEmployee.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="~/css/main.css" />
    <noscript><link rel="stylesheet" href="~/css/noscript.css" /></noscript>
</head>
<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper" class="fade-in">

        <!-- Intro -->
        <div id="intro">
            <h1>
                This is<br />
                Massively
            </h1>
            <p>
                Aenean ornare velit lacus varius enim ullamcorper proin aliquam,
                facilisis ante sed etiam magna interdum congue. Lorem ipsum dolor
            </p>
            <ul class="actions">
                <li><a href="#header" class="button icon solid solo fa-arrow-down scrolly">Continue</a></li>
            </ul>
        </div>

        <!-- Header -->
        <header id="header">
            <a href="index.html" class="logo">Massively</a>
        </header>

        <!-- Nav -->
        <nav id="nav">
            <ul class="links">
                <li class="active"><a asp-controller="Home" asp-action="Index">Main</a></li>
                <li><a asp-controller="Company" asp-action="List">List of Companies</a></li>
                <li><a asp-controller="Employee" asp-action="List">List of Employees</a></li>
            </ul>
            <ul class="icons">
                <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
                <li><a href="#" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
            </ul>
        </nav>

        <!-- Main -->
        <div id="main">

            <!-- Featured Post -->
            <article class="post featured">
                <header class="major">
                    <span class="date">April 25, 2017</span>
                    <h2>
                        <a href="#">
                            And this is a<br />
                            massive headline
                        </a>
                    </h2>
                    <p>
                        Aenean ornare velit lacus varius enim ullamcorper proin aliquam<br />
                        facilisis ante sed etiam magna interdum congue. Lorem ipsum dolor<br />
                        amet nullam sed etiam veroeros.
                    </p>
                </header>
                <a href="#" class="image main"><img src="images/pic01.jpg" alt="" /></a>
                <ul class="actions special">
                    <li><a asp-controller="Employee" asp-action="Create" class="button large">Add Employee</a></li>
                    <li><a asp-controller="Company" asp-action="Create" class="button large">Add Company</a></li>
                </ul>
            </article>

            <!-- Posts -->
            @RenderBody()

        </div>

        <!-- Footer -->
        @await Html.PartialAsync("FooterPartial")
    </div>
    <!-- Scripts -->
    @await Html.PartialAsync("ScripsPartial")

</body>
</html>